### ISSUE TITLE
ruby: Add feedback on indentation.

### ISSUE THREAD

**Issue by Insti** [exercism/rikki#17]
Many early problem solutions are filled with variable indentation.

Everyone* agrees that Ruby indentation is 2 spaces.

Rikki should give people polite reminders about this.

**Comment by kytrinyx** [comment]
Rikki has three different comments that it submits:

https://github.com/exercism/rikki/tree/master/comments/analyzer/ruby/indentation

I checked rikki's log, and it seems like it's these and submitting responses. (e.g. check out iteration two of hamming in Ruby by develaper. That's about tabs, not inconsistent spaces, though, so it might not be relevant).

I guess the first step in debugging would be to get the string from one such bit of code and submit it manually to http://analysseur.exercism.io and see if it returns a data set that includes `"indentation/inconsistent_spacing"`.

If you have concrete examples that aren't being caught, we should add tests for it in https://github.com/JacobNinja/exercism-analysis and redeploy the analysis API.

**Comment by Insti** [comment]
I think this has been resolved.
