### ISSUE TITLE
Hello Feedback could orient to page elements, seen and as yet unseen.

### ISSUE THREAD

**Issue by kotp** [exercism/rikki#19]
There is no mention to the "other things" that can happen with the exercise, such as archiving or requesting help from the 'manage' pull down.  Also, it could describe what isn't seen yet, but the soon to be seen such as `</>` buttons.

**Comment by kytrinyx** [comment]
Yeah, that would be helpful. I would be wary of talking about things you don't see yet. @troubalex do you have any resources you could point us to about good practices when onboarding someone in a new user interface that might talk about how to help orient them to specific ui elements?

**Comment by troubalex** [comment]
I have indeed. This might be helpful: http://www.appcues.com/blog/product-tours-when-to-use-which-ui-pattern/ The article lists different approaches to "tours" when the goal is to introduce particular features of a product/interface.

**Comment by kytrinyx** [comment]
Awesome, thanks!

**Comment by kotp** [comment]
Yay!  Proof that probot stale and won't fix is working correctly.

Anyone reading this, this is closed only due to "staleness" not that it is finished.  Feel free to reopen and continue the conversation when we are ready!
