### ISSUE TITLE
Rikki Welcome mesage for Hello on Bash

### ISSUE THREAD

**Issue by kotp** [exercism/rikki#22]
Would it be helpful to have Rikki orient people on this first exercise in Bash?

**Comment by kytrinyx** [comment]
Probably? What were you thinking of having Rikki say?

**Comment by kotp** [comment]
Something similar like Ruby intro does.  (or did... doesn't seem to be happening, I was clicking through the hello submissions, and don't see it happening).

`comments/hello/hello.md` basically.

**Comment by kytrinyx** [comment]
Oh. It was doing it on all of the languages for hello world, but the daemon might be down. I don't have monitoring. I'll check tonight.

**Comment by kytrinyx** [comment]
The rikki daemon was, indeed, down. I'm redeploying/restarting/troubleshooting now.

**Comment by kytrinyx** [comment]
Ref: https://github.com/exercism/discussions/issues/25

**Comment by kytrinyx** [comment]
The problem turned out to be that the redis URL for the new redis database wasn't publicly accessible. I've switched to a different redis provider that gives us a public URL. Rikki is now cooperating again: http://exercism.io/submissions/b15ddef10d1a428eaae670bce743ca53
