### ISSUE TITLE
[Ruby] rikki not posting a comment for initial hello-world submission

### ISSUE THREAD

**Issue by rpottsoh** [exercism/rikki#34]
I have noticed this behavior for the Ruby track, it may be true for others as well.  [This](http://exercism.io/submissions/97949fac3d964a179b2ab96c7abf245a) submission is missing a comment from Rikki.

**Comment by kytrinyx** [comment]
Rikki might be down, I'll check. Eventually we'll get monitoring on this!

**Comment by kytrinyx** [comment]
Yeah, it looks like Rikki is processing through a backlog now

**Comment by rpottsoh** [comment]
Looks like all is right again.  :+1:   Thanks @kytrinyx.
